# Generated by Django 3.2.25 on 2025-12-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=500, unique=True)),
                ('filepath', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('recording_date', models.DateField(db_index=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('fps', models.IntegerField(default=0)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('has_audio', models.BooleanField(default=False)),
                ('is_corrupted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cameras.camera')),
            ],
            options={
                'db_table': 'recordings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExportedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('filepath', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=0)),
                ('format', models.CharField(default='mp4', max_length=10)),
                ('export_date', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cameras.camera')),
                ('recordings', models.ManyToManyField(related_name='exports', to='recordings.Recording')),
            ],
            options={
                'db_table': 'exported_videos',
                'ordering': ['-export_date'],
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['camera', '-start_time'], name='recordings_camera__b9ad7c_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['camera', 'recording_date'], name='recordings_camera__4fe7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['-created_at'], name='recordings_created_e01ece_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['recording_date'], name='recordings_recordi_be04bd_idx'),
        ),
        migrations.AddIndex(
            model_name='exportedvideo',
            index=models.Index(fields=['camera', '-export_date'], name='exported_vi_camera__c7d5dd_idx'),
        ),
    ]
