# Generated by Django 3.2.25 on 2025-12-24 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('camera_type', models.CharField(choices=[('RTSP', 'RTSP Stream'), ('ONVIF', 'ONVIF Camera'), ('HTTP', 'HTTP Stream')], default='RTSP', max_length=10)),
                ('rtsp_url', models.CharField(max_length=500, validators=[django.core.validators.URLValidator()])),
                ('is_streaming', models.BooleanField(db_index=True, default=False)),
                ('is_recording', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('error', 'Error'), ('connecting', 'Connecting')], db_index=True, default='offline', max_length=20)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_frame_time', models.DateTimeField(blank=True, null=True)),
                ('reconnect_attempts', models.IntegerField(default=0)),
                ('auto_start_stream', models.BooleanField(default=False)),
                ('auto_start_recording', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cameras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_duration', models.IntegerField(default=300, help_text='Recording segment duration in seconds')),
                ('retention_days', models.IntegerField(default=7, help_text='Days to keep recordings')),
                ('stream_timeout', models.IntegerField(default=10, help_text='Stream timeout in seconds')),
                ('max_reconnect_attempts', models.IntegerField(default=5)),
                ('reconnect_delay', models.IntegerField(default=5, help_text='Delay between reconnection attempts in seconds')),
                ('max_storage_gb', models.IntegerField(default=100, help_text='Maximum storage in GB')),
                ('enable_failsafe_monitor', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Settings',
                'verbose_name_plural': 'Camera Settings',
                'db_table': 'camera_settings',
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['is_streaming', 'is_recording'], name='cameras_is_stre_243c22_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status'], name='cameras_status_3e06fd_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['-created_at'], name='cameras_created_f8bc70_idx'),
        ),
    ]
