# Generated by Django 3.2.25 on 2025-12-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Camera IP address or hostname', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, help_text='Camera password', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.IntegerField(default=554, help_text='RTSP port (usually 554)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_path',
            field=models.CharField(blank=True, help_text='Stream path (e.g., /cam/realmonitor?channel=1&subtype=0)', max_length=200),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, help_text='Camera username', max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
