# Generated by Django 3.2.25 on 2025-12-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_auto_20251224_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasettings',
            name='audio_bitrate',
            field=models.CharField(default='128k', help_text='Audio bitrate (64k, 128k, 256k)', max_length=10),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='audio_codec',
            field=models.CharField(default='aac', help_text='Audio codec (aac, mp3, copy, an)', max_length=20),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='video_codec',
            field=models.CharField(default='copy', help_text='Video codec (copy, libx264, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='video_format',
            field=models.CharField(default='mp4', help_text='Recording video format (mp4, mkv, mov, avi, ts)', max_length=10),
        ),
    ]
